name = "sppu-pyqs-db"
main = "src/index.ts"
compatibility_date = "2026-06-24"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "sppu-pyqs-db"
database_id = "0408fd80-6bef-4fbc-8910-472556114c08"

# DISCORD_WEBHOOK_URL is set with:
# wrangler secret put DISCORD_WEBHOOK_URL

[observability.logs]
enabled = true
invocation_logs = true
head_sampling_rate = 0.1
