"""Generate a local workflow status report from SQLite tracking."""

from __future__ import annotations

import argparse
import sys
from collections import Counter
from pathlib import Path

from common import tracking
from common.utils import INCOMING_DIR, NEEDS_REVIEW_DIR, PAPERS_DIR, PROJECT_ROOT
STATUS_PATH = PROJECT_ROOT / "docs" / "status.md"


def project_path(path: Path) -> str:
    try:
        return path.relative_to(PROJECT_ROOT).as_posix()
    except ValueError:
        return str(path)


def pdfs_under(directory: Path) -> list[Path]:
    if not directory.exists():
        return []
    return sorted(directory.rglob("*.pdf"))


def count_by_parts(files: list[Path], root: Path, max_depth: int = 4) -> Counter[str]:
    counts: Counter[str] = Counter()
    for path in files:
        try:
            parts = path.relative_to(root).parts
        except ValueError:
            continue
        key = "." if len(parts) <= 1 else "/".join(parts[: min(len(parts) - 1, max_depth)])
        counts[key] += 1
    return counts


def next_command(counts: Counter[str]) -> str:
    if counts["DISCOVERED"]:
        return "python3 tools/sync.py --files --apply"
    if counts["DOWNLOADED"] or counts["FOLDER_RENAMED"]:
        return "\n".join(
            [
                "python3 tools/rename_folders.py --create",
                "python3 tools/rename_folders.py --dry-run",
                "python3 tools/rename_folders.py",
                "python3 tools/rename_files.py --ocr-workers 1",
            ]
        )
    if counts["FILE_RENAMED"] or counts["NEEDS_REVIEW"]:
        return "python3 tools/verify.py"
    if counts["VERIFIED"]:
        return "python3 tools/move.py"
    if counts["MISSING"]:
        return "Run recovery workflow for MISSING rows."
    return "python3 tools/sync.py --folders"


def filesystem_drift(rows: list[dict]) -> Counter[str]:
    drift: Counter[str] = Counter()
    tracked_paths = {row.get("current_path") for row in rows if row.get("current_path")}
    for row in rows:
        current_path = row.get("current_path")
        if current_path and not (PROJECT_ROOT / current_path).exists():
            drift["tracked_path_missing"] += 1
    for root in (INCOMING_DIR, NEEDS_REVIEW_DIR, PAPERS_DIR):
        for pdf in pdfs_under(root):
            rel = project_path(pdf)
            if rel not in tracked_paths:
                drift["orphan_pdf"] += 1
    return drift


def render_folder_table(title: str, files: list[Path], root: Path) -> list[str]:
    lines = [f"## {title}", "", "| Folder | PDFs |", "| --- | ---: |"]
    counts = count_by_parts(files, root)
    if counts:
        lines.extend(f"| `{folder}` | {count} |" for folder, count in sorted(counts.items()))
    else:
        lines.append("| `none` | 0 |")
    lines.append("")
    return lines


def render_status() -> str:
    tracking.ensure_schema()
    rows = tracking.all_files()
    counts = tracking.counts_by_stage()
    incoming_files = pdfs_under(INCOMING_DIR)
    paper_files = pdfs_under(PAPERS_DIR)
    review_files = pdfs_under(NEEDS_REVIEW_DIR)
    reasons = tracking.needs_review_reasons()
    retries = tracking.retry_summary()
    drift = filesystem_drift(rows)

    lines = [
        "# SPPU PYQ Status",
        "",
        "Generated by `python3 tools/status.py`.",
        "",
        "## SQLite Tracking Counts",
        "",
        f"- Discovered: `{counts['DISCOVERED']}`",
        f"- Downloaded: `{counts['DOWNLOADED']}`",
        f"- Folder Renamed: `{counts['FOLDER_RENAMED']}`",
        f"- File Renamed: `{counts['FILE_RENAMED']}`",
        f"- Needs Review: `{counts['NEEDS_REVIEW']}`",
        f"- Verified: `{counts['VERIFIED']}`",
        f"- Moved: `{counts['MOVED']}`",
        f"- Missing: `{counts['MISSING']}`",
        "",
        "## Filesystem Counts",
        "",
        f"- Incoming PDFs: `{len(incoming_files)}`",
        f"- Papers PDFs: `{len(paper_files)}`",
        f"- Needs-review PDFs: `{len(review_files)}`",
        "",
        "## Needs Review Reasons",
        "",
    ]
    if reasons:
        lines.extend(f"- {name.replace('_', ' ').title()}: `{count}`" for name, count in sorted(reasons.items()))
    else:
        lines.append("- None: `0`")

    lines.extend(["", "## Retry Counts", ""])
    if retries:
        lines.extend(f"- {name}: `{count}`" for name, count in sorted(retries.items()))
    else:
        lines.append("- None: `0`")

    lines.extend(["", "## Filesystem Drift", ""])
    if drift:
        lines.extend(f"- {name.replace('_', ' ').title()}: `{count}`" for name, count in sorted(drift.items()))
    else:
        lines.append("- None: `0`")

    lines.extend(
        [
            "",
            "## Next Suggested Command",
            "",
            f"```bash\n{next_command(counts)}\n```",
            "",
        ]
    )
    lines.extend(render_folder_table("Papers By Folder", paper_files, PAPERS_DIR))
    lines.extend(render_folder_table("Incoming By Folder", incoming_files, INCOMING_DIR))
    lines.extend(render_folder_table("Needs Review By Folder", review_files, NEEDS_REVIEW_DIR))
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Write status.md with SQLite tracking counts and local workflow counts.")
    parser.add_argument("--print", action="store_true", dest="print_report", help="Print the report after writing status.md.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        report = render_status()
        STATUS_PATH.write_text(report, encoding="utf-8")
        print(f"Wrote {project_path(STATUS_PATH)}")
        if args.print_report:
            print()
            print(report)
        return 0
    except OSError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
